(defun tetris-at-start ()
  (setq actions-counter 0)
  (setq tetris-time (- (time-convert (current-time) 'integer) 1))
  (setq apm 0))

(defun actions-counter-up ()
  (setq actions-counter (+ actions-counter 1)))

(defun tetris-actions-per-minute (actions start-time last-time)
  (/ actions (/ (- last-time start-time) (float 60))))

(defun tetris-update-apm ()
  (actions-counter-up)
  (setq apm (tetris-actions-per-minute actions-counter tetris-time (time-convert (current-time) 'integer)))
  (message "%f" apm))


(defun new-tetris-start-game ()
  (interactive)
  (tetris-start-game)
  (tetris-at-start))
(defun new-tetris-move-bottom ()
  (interactive)
  (tetris-move-bottom)
  (tetris-update-apm))
(defun new-tetris-move-left ()
  (interactive)
  (tetris-move-left)
  (tetris-update-apm))  
(defun new-tetris-move-right ()
  (interactive)
  (tetris-move-right)
  (tetris-update-apm)) 
(defun new-tetris-rotate-prev ()
  (interactive)
  (tetris-rotate-prev)
  (tetris-update-apm))
(defun new-tetris-rotate-next ()
  (interactive)
  (tetris-rotate-next)
  (tetris-update-apm))
(defun new-tetris-move-down ()
  (interactive)
  (tetris-move-down)
  (tetris-update-apm))

(defvar tetris-mode-map
  (let ((map (make-sparse-keymap 'tetris-mode-map)))
    (define-key map "n"		'new-tetris-start-game)
    (define-key map "q"		'tetris-end-game)
    (define-key map "p"		'tetris-pause-game)

    (define-key map " "		'new-tetris-move-bottom)
    (define-key map [left]	'new-tetris-move-left)
    (define-key map [right]	'new-tetris-move-right)
    (define-key map [up]	'new-tetris-rotate-prev)
    (define-key map [down]	'new-tetris-move-down)
    (define-key map "a" 	'new-tetris-move-left)
    (define-key map "f"         'new-tetris-move-right)
    (define-key map "k"	        'new-tetris-rotate-prev)
    (define-key map "j"	        'new-tetris-rotate-next)
    (define-key map "d"	        'new-tetris-move-down)

    map)
  "Keymap for Tetris games.")

(defvar tetris-null-map
  (let ((map (make-sparse-keymap 'tetris-null-map)))
    (define-key map "n"		'new-tetris-start-game)
    (define-key map "q"         'quit-window)
    map)
  "Keymap for finished Tetris games.")


(tetris-at-start)
(message "Better tetris!!!")
